# Generated by Django 5.0 on 2024-05-27 19:42

import crimewatch.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('badge_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('tribe', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('nin', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=100)),
                ('distinctive_features', models.TextField(default='Scars, Tribal marks, Tattoos, Piercings, etc.')),
                ('next_of_kin', models.CharField(max_length=255)),
                ('finger_print', models.ImageField(upload_to='images/')),
                ('mugshot', models.ImageField(upload_to='images/')),
                ('known_aliases', models.CharField(max_length=255)),
                ('associates', models.CharField(max_length=255)),
                ('case_number', models.CharField(default=crimewatch.models.generate_case_number, max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(default='unknown', max_length=10)),
                ('rank', models.CharField(max_length=100)),
                ('badge_number', models.IntegerField()),
                ('area', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Nigerian', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(default=crimewatch.models.generate_case_number, max_length=9, unique=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('crime_type', models.CharField(max_length=255)),
                ('location_of_crime', models.CharField(max_length=255)),
                ('case_description', models.TextField()),
                ('associated_case_files', models.FileField(upload_to='files/')),
                ('witnesses', models.CharField(max_length=255)),
                ('known_suspects', models.CharField(max_length=255)),
                ('arrested_suspects', models.CharField(max_length=255)),
                ('case_status', models.CharField(max_length=100)),
                ('pictures_of_evidence', models.ImageField(upload_to='images/')),
                ('associated_criminals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimewatch.criminalrecord')),
                ('case_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimewatch.policeofficers')),
            ],
        ),
    ]
